### ISSUE TITLE
server error connecting  when connecting sometimes

### ISSUE THREAD

**Issue by dannygoldstein** [dmitryduev/broker#1]
This can happen randomly. 

```
Traceback (most recent call last):
  File "ztf.py", line 19, in <module>
    k = penquins.Kowalski(username=REDACTED, password=REDACTED)
  File "/global/cscratch1/sd/dgold/lsn/install/lib/python3.6/site-packages/penquins.py", line 46, in __init__
    self.access_token = self.authenticate()
  File "/global/cscratch1/sd/dgold/lsn/install/lib/python3.6/site-packages/penquins.py", line 90, in authenticate
    if 'token' not in auth.json():
  File "/global/cscratch1/sd/dgold/lsn/install/lib/python3.6/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.6/site-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3.6/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by dmitryduev** [comment]
Most likely this happens when the server runs out of available connections, which wasn't properly handled in the penquins.py library. Added a "retries" parameter, which defaults to 3, see [here](https://github.com/dmitryduev/kowalski/commit/40096b874296aac2b6f7202f4d34bcd650d37ceb)
